import React, { Component } from "react";
import { Table, Card, Button, Spinner, Modal } from "react-bootstrap";

export class ConductAuction extends Component {
  render() {
    return (
      <React.Fragment>
        <Card.Header style={{ fontWeight: "bold" }}>
          <p style={{ textAlign: "center", margin: "0" }}>Live Routes List</p>
        </Card.Header>
        <Table striped bordered hover responsive size="sm">
          <thead>
            <tr>
              <th>Mandi\Godowns</th>
              <th>FCI</th>
              <th>FCI</th>
              <th>Markfed</th>
              <th>Markfed</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Abohar</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Rajjanaali</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Seedfarm</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Sitto</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Abohar</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Rajjanaali</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Seedfarm</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Sitto</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Abohar</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Rajjanaali</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Seedfarm</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Sitto</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Abohar</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Rajjanaali</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Seedfarm</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
            <tr>
              <td>Sitto</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
              <td>69/96</td>
            </tr>
          </tbody>
        </Table>
      </React.Fragment>
    );
  }
}

export default ConductAuction;
